# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Open_Voicing.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import data_basa
import json
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1188, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 240, 180, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 240, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 270, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(630, 30, 531, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(150, 170, 277, 120))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_15.addWidget(self.label_21)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_15.addWidget(self.lineEdit_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_10.addWidget(self.label_17)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_10.addWidget(self.pushButton_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_10)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_10.addWidget(self.comboBox_3)
        self.verticalLayout_15.addLayout(self.verticalLayout_10)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(160, 60, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(150, 120, 277, 43))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_12.addWidget(self.lineEdit_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_13.addWidget(self.label_19)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_13.addWidget(self.lineEdit_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_14.addWidget(self.lineEdit_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(140, 20, 281, 404))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_4.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_4.addWidget(self.radioButton_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_6.addWidget(self.lineEdit_3)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_7.addWidget(self.lineEdit_4)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_8.addWidget(self.lineEdit_6)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_9.addWidget(self.lineEdit_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_9)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_3.addWidget(self.comboBox_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1188, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.MainQuestions = []

        #---------------------Сигналы и Слоты------------------------
        self.BAZA = data_basa.Basa()
        self.getUsers()
        self.pushButton_5.clicked.connect(self.Create_Trans_Add_Open_Voicing)
        self.pushButton_3.clicked.connect(self.Add_Questions)
        self.pushButton_4.clicked.connect(self.Create_Trans_Add_Closed_Voicing)
        self.Get_Active_Vouting()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Открытое голосование"))
        self.label_2.setText(_translate("MainWindow", "ФИО"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "Дожность"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "Доступные Голосования"))
        self.radioButton.setText(_translate("MainWindow", "За "))
        self.radioButton_2.setText(_translate("MainWindow", "Против"))
        self.pushButton.setText(_translate("MainWindow", "Проголосовать"))
        self.pushButton_2.setText(_translate("MainWindow", "Предложить Свою Кандидатуру"))
        self.label_21.setText(_translate("MainWindow", "Длительность"))
        self.label_17.setText(_translate("MainWindow", "Пользователи"))
        self.pushButton_5.setText(_translate("MainWindow", "Предложить исключить"))
        self.label_15.setText(_translate("MainWindow", "Добавить открытое голосование"))
        self.label_18.setText(_translate("MainWindow", "День"))
        self.label_19.setText(_translate("MainWindow", "Месяц"))
        self.label_20.setText(_translate("MainWindow", "Год"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab),
                                  _translate("MainWindow", "Добавить Открытое голосование"))
        self.label_10.setText(_translate("MainWindow", "Добавить закрытое голосование"))
        self.label_9.setText(_translate("MainWindow", "Название голосования:"))
        self.label_5.setText(_translate("MainWindow", "Добавить варианты ответов:"))
        self.radioButton_3.setText(_translate("MainWindow", "Для преподователей"))
        self.radioButton_4.setText(_translate("MainWindow", "Для студентов"))
        self.label_11.setText(_translate("MainWindow", "День"))
        self.label_12.setText(_translate("MainWindow", "Месяц"))
        self.label_13.setText(_translate("MainWindow", "Год"))
        self.label_14.setText(_translate("MainWindow", "Длительность"))
        self.pushButton_3.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_4.setText(_translate("MainWindow", "Создать голосование"))
        self.label_4.setText(_translate("MainWindow", "Варианты голосов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2),
                                  _translate("MainWindow", "Добавить закрытое голосование"))

    def Get_Active_Vouting(self):
       # Vouting = self.BAZA.get_active_open_voting('0001')#Test
        #print(Vouting[0].get('fio'))
       # self.comboBox.addItem(Vouting[0].get('fio'))

    def Add_Questions(self):
        qustion = self.lineEdit.text()
        self.MainQuestions.append(qustion)
        self.comboBox_2.addItem(qustion)
        print(self.MainQuestions)
    def getUsers(self):
        temp = self.BAZA.get_users()
        for i in range(len(temp)):
            self.comboBox_3.addItem(temp[i].get('fio'))
    def Create_Trans_Add_Closed_Voicing(self):
        NumberTransction = 12
        voicnhName = self.lineEdit_2.text()
        day = self.lineEdit_3.text()
        month = self.lineEdit_4.text()
        year = self.lineEdit_6.text()
        day = int(day)
        month = int(month)
        year = int(year)
        AdminKey = 'Test_Key112233445566778899aabbcc'
        signature = 'Test_Signature'
        print(voicnhName)
        quustions =[]
        quustions.append(voicnhName)
        print(quustions)
        for i in range(len(self.MainQuestions)):
            quustions.append(self.MainQuestions[i])
        #quustions.append(self.MainQuestions)
        during = quustions
        print(during)
        role = 0
        data = {}
        transaction = {}
        if self.radioButton_4.isChecked()==True:
            role = int(1)
            print(role)
            data.update({"role":role})
            data.update({'day':day})
            data.update({'month':month})
            data.update({'year':year})
            data.update({'during':during})
            data = json.dumps(data)
            transaction.update({'ok': AdminKey})
            transaction.update({'type': 'transaction'})
            transaction.update({'code': NumberTransction})
            transaction.update({'data': data})
            transaction.update({'sign': signature})
            transaction = json.dumps(transaction)

        if self.radioButton_3.isChecked()==True:
            role = int(2)
            data.update({"role": role})
            data.update({'day': day})
            data.update({'month': month})
            data.update({'year': year})
            data.update({'during': during})
            data = json.dumps(data)
            transaction.update({'ok': AdminKey})
            transaction.update({'type': 'transaction'})
            transaction.update({'code': NumberTransction})
            transaction.update({'data': data})
            transaction.update({'sign': signature})
            transaction = json.dumps(transaction)
    def Create_Trans_Add_Open_Voicing(self):
        NumberTransaction = 11
        UserName = self.comboBox_3.currentText()
        candidate_Ok = self.BASA.get_OKo_by_user(UserName)
        AdminKey = 'Test_Key112233445566778899aabbcc'
        signature = 'Test_Signature'
        print(candidate_Ok)
        OK = 'Требуется Accaount system'
        day =  self.lineEdit_8.text()
        mounth = self.lineEdit_9.text()
        year = self.lineEdit_10.text()
        during = self.lineEdit_11.text()
        day = int(day)
        mounth = int(mounth)
        year = int(year)
        during = int(during)
        data = {}
        transaction ={}
        data.update({'OK':OK})
        data.update({'condidate_OK':candidate_Ok})
        data.update({'day':day})
        data.update({'month':mounth})
        data.update({'year':year})
        data.update({'during':during})
        data = json.dumps(data)
        transaction.update({'ok': AdminKey})
        transaction.update({'type': 'transaction'})
        transaction.update({'code': NumberTransaction})
        transaction.update({'data': data})
        transaction.update({'sign': signature})
        transaction = json.dumps(transaction)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

